system:
  web_port: 8080
  mediamtx_api_port: 9997
  mediamtx_webrtc_port: 8889
  default_username: admin
  default_password: '12345678'
  auto_start: false
  language: pt-BR
  first_run: false
recording:
  segment_duration: 900
  retention_days: 7
  recordings_path: recordings
cloud:
  provider: gdrive
  enabled: true
  sync_interval_minutes: 60
  bandwidth_limit: 5M
  remote_name: sentinela
  remote_path: Sentinela
tunnel:
  mode: quick
  public_url: https://behavior-defines-lancaster-previously.trycloudflare.com
  hostname: null
  tunnel_name: null
cameras:
- id: camera-1
  name: Camera XM Sala
  ip: 192.168.15.8
  port: 554
  username: admin
  password: ''
  channel: 0
  stream: 0
  brand: icsee
  codec: h265
  enabled: true
  status: offline
- id: camera-2
  name: Camera XM (10)
  ip: 192.168.15.10
  port: 554
  username: admin
  password: ''
  channel: 1
  stream: 0
  brand: icsee
  codec: h265
  enabled: true
  status: offline
- id: camera-3
  name: Camera XM (11)
  ip: 192.168.15.11
  port: 554
  username: admin
  password: ''
  channel: 0
  stream: 0
  brand: icsee
  codec: h265
  enabled: true
  status: offline
